settings_version: 0.0.4
datasets_dir: /Users/hrishikesh/Desktop/Video Redaction/backend/datasets
weights_dir: weights
runs_dir: runs
uuid: c788ac416e00eb57aae7dce15c86a2c925bd9fdd7932994fb9a0c4590524512e
sync: true
api_key: ''
openai_api_key: ''
clearml: true
comet: true
dvc: true
hub: true
mlflow: true
neptune: true
raytune: true
tensorboard: true
wandb: true
